name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: ppt2video_db_user
          POSTGRES_DB: ppt2video_poc
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up environment variables
      run: |
        echo "PPT2VIDEOPOC_DB_PWD=test_password" >> $GITHUB_ENV
        echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV

    - name: Check code formatting with Spotless
      working-directory: backend
      run: mvn spotless:check

    - name: Compile and package
      working-directory: backend
      run: mvn clean install -DskipTests

    - name: Run tests
      working-directory: backend
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ppt2video_poc
        SPRING_DATASOURCE_USERNAME: ppt2video_db_user
        SPRING_DATASOURCE_PASSWORD: test_password

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: backend-build
        path: backend/target/*.jar
        retention-days: 1