name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        # Install root dependencies
        npm ci
        # Force clean install in frontend to ensure platform binaries are installed
        cd frontend
        rm -rf node_modules package-lock.json
        npm install
        # Explicitly install platform-specific binaries
        npm install --no-save --force @rollup/rollup-linux-x64-gnu @swc/core-linux-x64-gnu
        # Debug: Check if the binaries are installed
        echo "Checking for rollup binary:"
        ls -la node_modules/@rollup/ || true
        echo "Checking rollup package:"
        ls -la node_modules/rollup/dist/ || true

    - name: Type check
      working-directory: frontend
      run: npx tsc --noEmit

    - name: Run ESLint
      working-directory: frontend
      run: npm run lint

    - name: Build frontend
      working-directory: frontend
      run: npm run build
      env:
        VITE_API_URL: http://localhost:8080/api

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: frontend-build-node-${{ matrix.node-version }}
        path: frontend/dist/
        retention-days: 7

    - name: Run build size analysis
      working-directory: frontend
      run: |
        if [ -d "dist" ]; then
          echo "Build size analysis:"
          du -sh dist/
          find dist -name "*.js" -exec wc -c {} + | sort -n
        fi