name: Full CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml
    
  frontend:
    uses: ./.github/workflows/frontend-ci.yml
    
  integration:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ppt2video_poc_test
          POSTGRES_USER: ppt2video_db_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: backend/target

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Verify backend startup and health
      run: |
        # Start the backend using the built JAR
        # Set JPA to validate only (not create/update) to avoid conflicts with Flyway
        java -jar backend/target/*.jar \
          --spring.profiles.active=test \
          --spring.jpa.hibernate.ddl-auto=none &
        BACKEND_PID=$!
        
        # Wait for startup
        echo "Waiting for backend to start..."
        sleep 30
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f http://localhost:8080/api/health || exit 1
        echo "Health check passed!"
        
        # Clean up
        kill $BACKEND_PID
      env:
        PPT2VIDEOPOC_DB_PWD: test_password
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ppt2video_poc_test
        SPRING_DATASOURCE_USERNAME: ppt2video_db_user
        SPRING_DATASOURCE_PASSWORD: test_password