name: Starter remove
on: [workflow_dispatch]
jobs:
  remove-job:
    runs-on: ubuntu-latest
    steps:
    - id: result 
      uses: MichaelMelena/list-artifacts@v1
    - uses: MichaelMelena/remove-artifacts@v1
      with:
        artifacts: ${{ steps.result.outputs.artifacts }}
